### ISSUE TITLE
Issue with event names

### ISSUE THREAD

**Issue by TokcDK** [denikson/COM3D2.i18nEx#1] opened 2019-08-02 13:41 UTC
Made dump from english version. Moved dumped folders to i18nEx\English folder and then moved i18nEx to japanese version. All normal in game and oficial english is better and especially better than g. autotranslation. Noticed when selected language English and Japanese then displaying text on both languages but this is not a so issue.
Main issue this is when opened Events notice instead of some event names displaying number and "title" word in japanese and kind of same for event description. For example Name = "2420/title" and Description = "2420/Content".
Issue appeared right after ForceEnglishUI was removed and this plugin added with dump.

Maybe it was already fixed in one of latest commits here as problem with creating dump but anyway added issue for any case.

**Comment by ghorsington** [comment] 2019-08-02 13:44
Greetings!

Thanks for pointing that out. The issue is known and has been fixed by adding a fallback mechanism to Japanese text in 8a7b92b9.

The new release with the fix is coming out as soon as a few other problems are solved.

**Closed as completed by ghorsington** 2019-08-02 13:44 UTC

**Comment by TokcDK** [comment] 2019-08-02 13:46
OK. Understood. Thank you for good plugin.
